### PR TITLE
Only copy headers once (in global init)

### LINKED ISSUE #40: COPY TO with SQL statements repeats the header rows
If you select rows in the copy statement and union them, then the rows are written one by one, and the header row is duplicated

```sql 
copy (
    select 'Microsoft' as company, 'Excel' as product, 1985 as year_founded
    union all
    select 'Google', 'Google Sheets', 2006
    union all
    select 'Apple', 'Numbers', 1984
    union all
    select 'LibreOffice', 'Calc', 2000) 
to 'https://docs.google.com/spreadsheets/d/11QdEasMWbETbFVxry-SsD8jVcdYIT1zBQszcF84MdE8/edit?gid=1295634987#gid=1295634987' (format gsheet);
```

Result

company | product | year_founded
-- | -- | --
Microsoft | Excel | 1985
company | product | year_founded
Google | Google Sheets | 2006
company | product | year_founded
Apple | Numbers | 1984
company | product | year_founded
LibreOffice | Calc | 2000

### PR DESCRIPTION
**Pull request by Alex-Monahan**
Fixes #40. Had to duplicate some code, but it was sliiiightly different than the Sink implementation.

Also adds 2 tests to make sure this stays working!

### CODE REVIEW

**Comment by archiewood** [comment]
Looks awesome!

**Comment by archiewood** [comment]
the test is somewhat insane but i'm here for it

**Comment by Alex-Monahan** [comment]
It had to be over 2048, so i went 1 decimal place higher...haha

**Comment by archiewood** [comment]
Yeah I'm not too worried. 

Maybe in the future we can read it back with a count(*) to check number of rows that we wrote

**Pull request merged**
