### PR TITLE
Handle first row blanks, parse booleans correctly, "" in varchars should be NULL

### PR DESCRIPTION
**Pull request by Alex-Monahan**
Let me know what you think!

Would you be open to doing a release to the community repo at some point in the next few weeks (post holidays is fine for sure!).

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Also figured out how to just parse the return types once! Not sure what the CI failures were (it is re-running with this commit)

**Comment by Alex-Monahan** [comment]
Howdy Archie! I believe the CI failures are unrelated. The error messages seem to indicate something that is up with deployment and not building.

**Comment by archiewood** [comment]
> Would you be open to doing a release to the community repo at some point in the next few weeks (post holidays is fine for sure!).

Yes, let's do a release when this merges. Maybe will fix the issue with 0.0.3

**Comment by archiewood** [comment]
A bump seems to have fixed the tests

**Comment by archiewood** [comment]
or not...

**Comment by samansmink** [comment]
The artifact upload step is using v4 whereas the download step is on v3 because that is checked into the extension repo and has fallen behind.

You can probably consider removing the local deploy workflow as we have done recently in the extension template https://github.com/duckdb/extension-template/pull/98

**Comment by archiewood** [comment]
Okay great, will merge this and remove deploy in separate PR

**Pull request merged**
